timeout: 3

/StrawOS
    protocol: limine
    path: boot():/boot/kernel

    resolution: 1440x900x32

    module_path: boot():/modules/bin/doomgeneric.elf
    module_path: boot():/modules/doom1.wad
    module_path: boot():/modules/bin/test.lua