timeout: 3

/StrawOS
    protocol: limine
    path: boot():/boot/kernel

    resolution: 1440x900x32

    module_path: boot():/modules/bin/shell.elf
    module_path: boot():/modules/bin/doomgeneric.elf
    module_path: boot():/modules/doom1.wad
    module_path: boot():/modules/bin/test.lua

    module_path: boot():/modules/bin/ls.elf
    module_path: boot():/modules/bin/mkdir.elf
    module_path: boot():/modules/bin/clear.elf
    module_path: boot():/modules/bin/cat.elf
    module_path: boot():/modules/bin/echo.elf
    module_path: boot():/modules/bin/rm.elf
    module_path: boot():/modules/bin/pwd.elf
    module_path: boot():/modules/bin/ps.elf
    module_path: boot():/modules/bin/kill.elf