timeout: 3

/StrawOS
    protocol: limine
    path: boot():/boot/kernel

    resolution: 1440x900x32

    module_path: boot():/modules/hello_world.txt
    module_path: boot():/modules/test.elf
    module_path: boot():/modules/cabin.bmp
    module_path: boot():/modules/viking_room.bmp
    module_path: boot():/modules/viking_room.obj